# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74467be79801bb76237dc847879ae86e3d933a89b4bca863dc83a2afca3c24bc59ed14655b1036990d065fbbe5bba3f66e60541e4c6ed51541226f516e32ffef

test:
  secret_key_base: 0546f007b5e5e8aed2fe2435e518938b591630e58bf3412be54c2edd740cab4bfc3399a26dd46f66e0bb157a48fb91a5adc4b23c748c66a96deb8b6a095c7874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
